[theme]
# Ensure a consistent blue primary color across all Streamlit sessions.
primaryColor = "#2E7FF1"
# Optional complementary colors to keep the palette cohesive.
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FF"
textColor = "#1F2933"
base = "light"
